apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-votingapp-canary
  namespace: prod-canary
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx-prod
  rules:
  - host: brief8-prod.simplon-lion.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: votingapp-v2
            port:
              number: 80
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - brief8-prod.simplon-lion.space
    secretName: secret-tls # < cert-manager will store the created certificate in this secret.

