apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          args: ["--requirepass", "$(REDIS_PWD)"]
          env:
            - name: REDIS_PWD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_PWD
          volumeMounts:
            - name: diskredis
              mountPath: /data
      volumes:
        - name: diskredis
          persistentVolumeClaim:
            claimName: redis-pvc
